### PR TITLE
Remove whitespace in mtu setting

### PR DESCRIPTION
**Pull request by cotsog**
Hello! I'm a support engineer from Travis CI.

I think this should work better.

Let me know the result.

Thanks!

### CODE REVIEW

**Comment by BerkhanBerkdemir** [comment]
That didn't work out, @cotsog. I checked the logs and the reason is just the same [0]. Is there any other changes that Travis CI did for Docker?

\[0]: https://travis-ci.org/magara/magara/jobs/592864626#L958

**Comment by cotsog** [comment]
@BerkhanBerkdemir I've pushed another commit and now the error in the build is different:

https://travis-ci.org/magara/magara/jobs/593128891#L1256

Can you have a look? Thanks!

**Comment by BerkhanBerkdemir** [comment]
> @BerkhanBerkdemir I've pushed another commit and now the error in the build is different:
> 
> https://travis-ci.org/magara/magara/jobs/593128891#L1256
> 
> Can you have a look? Thanks!

Yes, I did check out the result, @cotsog. We need to update our `Dockerfile` :man_facepalming:. I will merge this changes to `feature/create-container` branch with updated `Dockerfile`.

Thank you for your contribution :blue_heart:

**Comment by cotsog** [comment]
I confirm you only need this change in the jobs you need Docker. So probably just under your `install_docker` anchor. Let me fix that.

**Pull request merged**
