### PR TITLE
Refactor houses helper and controller

### LINKED ISSUE #49: Fixing coding style for Houses
Hey @hoangvq288,

Your work on PR #33 was awesome. I just wanted you to remember it. The PR was about fixing coding style for `HousesHelper.rb` and `HousesController.rb`.

> Also, I'm looking a contributor who can get rid off linter warnings.

### PR DESCRIPTION
**Pull request by NARKOZ**
Fixes #49

### CODE REVIEW

**Comment by BerkhanBerkdemir** [comment]
Welcome @NARKOZ,

I know, you were the fastest one, but #53 does a lot. However, I love [that line](https://github.com/magara/magara/pull/52/files#diff-fb0825b6ddd7cbef5bbe25d51689ba2aR19), so can we use that line for PR #53?

**Comment by BerkhanBerkdemir** [comment]
@NARKOZ, thank you for that PR, but #53 is detailed now. I'd like to see your new PRs in the feature :heart:.

Duplicate of #53

**Comment by NARKOZ** [comment]
@BerkhanBerkdemir you should first check creation time. Actually another one is duplicate

**Comment by BerkhanBerkdemir** [comment]
Well, you were right, @NARKOZ. Sorry :cry:

**Pull request closed without merging**
